project_id: gaming-keyboard-2025-09-07
created_at: 2025-09-07T12:00:00
status: initialized
category: ゲーミングキーボード
target_audience: 20-30代男性ゲーマー
budget_range: 1-3万円
workflow_version: PA-API実装完了版
estimated_time: 15-20分